name: second workflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "we are able to start the second workflow"
      - name: print message
        run: echo "yes,excited"
  

